#%RAML 1.0 NamedExample
value:
  record:
    properties: 
      id: integer
      first_name: string
      last_name: string
      gender: string
      ip_address: string
      email:
        properties:
          main: string
          other: string